### ISSUE TITLE
[auth] flaky test "Generating QR code value"

### ISSUE THREAD

**Issue by eventualbuddha** [votingworks/vxsuite#4061]
```
 FAIL  src/live_check.test.ts
  ● Generating QR code value

    expect(received).toHaveLength(expected)

    Expected length: 655
    Received length: 651
    Received string: "1//lc//0000/2023-10-09T23:31:33.609Z/63338144e0;MEMCHzeFbPby7BsJinvePHdx48WoGNQEG0XWBPorGcRywMYCIE+tl4c8LcmQ6eXPnXQfUjJ7DhJMH8/pCqR29aol0q5m;
    MIIBczCCARgCFG7moIqicUXiMSJNE8qjeCxf8QY7MAoGCCqGSM49BAMCMDAxCzAJ
    BgNVBAYTAlVTMQswCQYDVQQIDAJDQTEUMBIGA1UECgwLVm90aW5nV29ya3MwIBcN
    MjMwOTA1MTc0NzA0WhgPMjEyMzA4MTIxNzQ3MDRaMEUxCzAJBgNVBAYTAlVTMQsw
    CQYDVQQIDAJDQTEUMBIGA1UECgwLVm90aW5nV29ya3MxEzARBgkrBgEEAYPTKQEM
    BHNjYW4wWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAQcpAy0eXi9ZLH1BiWE3Sko
    HJYTBxbsvB2CRyU7qbl+XeZlVlPBI6XjyIdLgzfC3vOSW20Gp7W54cPFr/ue+l52
    MAoGCCqGSM49BAMCA0kAMEYCIQCgwgx3BNd9qNSlGJUPvYPjzjvChUoHXldUHa+R
    hTYTSgIhAL9buyXFO9U3693Z5vGqhUDqPz+Ua/iSNjxi3XVirAt/·
    "

      65 |       electionHash: isMachineConfiguredForAnElection ? electionHash : undefined,
      66 |     });
    > 67 |     expect(qrCodeValue).toHaveLength(expectedQrCodeValueLength);
         |                         ^
      68 |   }
      69 | );
      70 |

      at src/live_check.test.ts:67:25
```

**Comment by eventualbuddha** [comment]
Another one:

```
 FAIL  src/live_check.test.ts
  ● Generating QR code value

    expect(received).toHaveLength(expected)

    Expected length: 818
    Received length: 814
    Received string: "1//lc//0000/2023-12-01T00:23:27.695Z/63338144e0;MEMCHwCBXTVabVtNk0tbFjrG3eNxkH0hZCEiyKxPqUfvoikCIFHqkCUP1sp9Ccrp5r3DIwBbRpXaw25LToG/Wo6s+0Z3;
    MIIB6TCCAZCgAwIBAgIUbuagiqJxReIxIk0TyqN4LF/xBjgwCgYIKoZIzj0EAwIw
    MDELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAkNBMRQwEgYDVQQKDAtWb3RpbmdXb3Jr
    czAgFw0yMzA5MDUxNzQ3MDRaGA8yMTIzMDgxMjE3NDcwNFowYzELMAkGA1UEBhMC
    VVMxCzAJBgNVBAgMAkNBMRQwEgYDVQQKDAtWb3RpbmdXb3JrczEUMBIGCSsGAQQB
    g9MpAQwFYWRtaW4xGzAZBgkrBgEEAYPTKQIMDGp1cmlzZGljdGlvbjBZMBMGByqG
    SM49AgEGCCqGSM49AwEHA0IABNio3BNNm2REYd3fqEHRwKeWOIOyhtEEE/FrhFh5
    l8SYISezpoUBoNLCwEcR0ngeBu6+eCz2Exi8MHaTJoVX2KujUzBRMB0GA1UdDgQW
    BBTtjdGcruKPdtnlwoOBiAW+1F4AwjAfBgNVHSMEGDAWgBTWDPrS8ELb/2gAtgIg
    gNXI9kP8GDAPBgNVHRMBAf8EBTADAQH/MAoGCCqGSM49BAMCA0cAMEQCIDV3otni
    w8zEMrAppdzZ6DtxXeugtrEQEON0faHU58j+AiAK5bKumrya/DhH402wyuz8+CoD
    UPv/iORaItaY6lIckw==·
    "

      65 |       electionHash: isMachineConfiguredForAnElection ? electionHash : undefined,
      66 |     });
    > 67 |     expect(qrCodeValue).toHaveLength(expectedQrCodeValueLength);
         |                         ^
      68 |   }
      69 | );
      70 |

      at src/live_check.test.ts:67:25
```

**Comment by benadida** [comment]
I think this is stale.
