### ISSUE TITLE
Pressing "System Diagnostics" in pollworker menu breaks the app

### ISSUE THREAD

**Issue by kshen0** [votingworks/vxsuite#4468]

**Comment by kshen0** [comment]
```
Error occurred in handler for 'setClock': Error: Failed to set time: Automatic time synchronization is enabled

    at /opt/kiosk-browser/resources/app.asar/build/src/ipc/clock.js:25:23
    at async node:electron/js2c/browser_init:193:563
Error occurred in handler for 'setClock': Error: Failed to set time: Automatic time synchronization is enabled

    at /opt/kiosk-browser/resources/app.asar/build/src/ipc/clock.js:25:23
    at async node:electron/js2c/browser_init:193:563
Error occurred in handler for 'setClock': Error: Failed to set time: Automatic time synchronization is enabled

    at /opt/kiosk-browser/resources/app.asar/build/src/ipc/clock.js:25:23
    at async node:electron/js2c/browser_init:193:563`
```

**Comment by kshen0** [comment]
Also breaks when "Reset Accessible Controller" button is pressed

**Comment by kshen0** [comment]
Sorry, this issue was not fleshed out well. This issue was for the old Poll Worker System Diagnostics, so we were guessing merging https://github.com/votingworks/vxsuite/pull/4676 would allow us to close.

**Comment by kshen0** [comment]
Looking at the code for the page from the time this bug was filed, I'm not sure how we could have invoked setting system clock from selecting the "System Diagnostics" button. I also can't repro on latest main with your changes in, so I'm going to close this.
